version: "3"
services:
  mariadb:
    image: mariadb:10.2
    container_name: mariadbfr
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: filerun
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
    restart: on-failure
    volumes:
     - $PWD/data/database:/var/lib/mysql
  filerun:
    #image: afian/filerun
    image: ponte124/filerun:latest-arm64v8
    container_name: filerun
    environment:
      FR_DB_HOST: mariadbfr
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: filerun
      FR_DB_PASS: filerun
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    volumes:
      - $PWD/data/filerun/html:/var/www/html
      - $PWD/data/filerun/user-files:/user-files
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9090:80
    restart: on-failure
    depends_on:
      - mariadb
    links:
      - mariadb    